name: gis
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1
  - attrs=22.1.0
  - blosc=1.21.1
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotlipy=0.7.0
  - contourpy=1.0.6
  - cryptography=38.0.4
  - curl=7.86.0
  - cycler=0.11.0
  - cykhash=2.0.0
  - cython=0.29.32
  - expat=2.5.0
  - fiona=1.8.22
  - folium=0.13.0
  - freexl=1.0.6
  - gdal=3.5.3
  - geopandas=0.12.1
  - geos=3.11.1
  - geotiff=1.7.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - jinja2=3.1.2
  - kiwisolver=1.4.4
  - mapclassify=2.4.3
  - matplotlib-base=3.6.2
  - munch=2.5.0
  - munkres=1.1.4
  - netcdf4=1.6.2
  - networkx=2.8.8
  - numpy=1.23.5
  - pandas=1.5.2
  - pillow=9.2.0
  - pip=22.3.1
  - pixman=0.40.0
  - poppler=22.11.0
  - proj=9.1.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyproj=3.4.0
  - pyrobuf=0.9.3
  - pyrosm=0.6.1
  - pysocks=1.7.1
  - rasterio=1.3.3
  - rasterstats=0.17.0
  - requests=2.28.1
  - rtree=1.0.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - shapely=1.8.5
  - simplejson=3.18.0
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - threadpoolctl=3.1.0
  - tiledb=2.11.3
  - tk=8.6.12
  - urllib3=1.26.13
  - wheel=0.38.4
  - xerces-c=3.2.4